"""empty message

Revision ID: 3396ddeaed97
Revises: 
Create Date: 2024-05-30 11:25:28.899086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3396ddeaed97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_member')
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_owed_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_owing_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_owed_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_owing_id'], ['id'])
        batch_op.drop_column('user_to_id')
        batch_op.drop_column('user_from_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_from_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('user_to_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_to_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_from_id'], ['id'])
        batch_op.drop_column('user_owing_id')
        batch_op.drop_column('user_owed_id')

    op.create_table('group_member',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
