"""add debt

Revision ID: d08f341b9685
Revises: ff7618b04218
Create Date: 2024-06-02 13:56:04.772217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08f341b9685'
down_revision = 'ff7618b04218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debt_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debt_user',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('debt_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['debt_id'], ['debt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###
